dubbo:
  application:
    #应用名称
    name: dubbo-provider
  registry:
    #注册中心地址
    address: zookeeper://127.0.0.1:2181
  scan:
    #扫描服务类包目录
    base-packages: org.willwu.dubboProvider.service
  protocol:
    #协议名称
    name: dubbo
    #协议端口
    port: 20880
server:
  port: 8087